import {
  AstNode,
  AstNodeType,
  IncludeDirectiveNode,
  MixinDefinitionNode,
  PropertyDeclarationNode,
  RuleNode,
  Token,
  TokenType,
  VariableDeclarationNode
} from "./types";

/**
 * Parser that converts a stream of SCSS tokens into an Abstract Syntax Tree.
 */
export class Parser {
  private readonly tokens: Token[];
  private current: number = 0;

  /**
   * Initializes a new Parser instance.
   * @param tokens The array of tokens generated by the Tokenizer.
   */
  constructor(tokens: Token[]) {
    this.tokens = tokens;
  }

  /**
   * Parses the complete token stream into an array of root-level AST nodes.
   * @returns An array of top-level AstNode elements.
   */
  public parse(): AstNode[] {
    const nodes: AstNode[] = [];

    while (!this.isAtEnd()) {
      const node = this.parseStatement();
      if (node !== null) {
        nodes.push(node);
      }
    }

    return nodes;
  }

  private parseStatement(): AstNode | null {
    const token = this.peek();

    if (token.type === TokenType.EndOfFile) {
      return null;
    }

    if (token.type === TokenType.Variable) {
      return this.parseVariableDeclaration();
    }

    if (token.type === TokenType.AtKeyword) {
      if (token.value === "@mixin") {
        return this.parseMixinDefinition();
      }
      if (token.value === "@include") {
        return this.parseIncludeDirective();
      }
    }

    return this.parseRuleOrProperty();
  }

  private parseVariableDeclaration(): VariableDeclarationNode {
    const varToken = this.consume(TokenType.Variable, "Expected variable name");
    this.consume(TokenType.Colon, "Expected ':' after variable name");

    const valTokens: Token[] = [];
    while (!this.isAtEnd() && this.peek().type !== TokenType.Semicolon && this.peek().type !== TokenType.CloseBrace) {
      valTokens.push(this.advance());
    }

    if (this.peek().type === TokenType.Semicolon) {
      this.advance();
    }

    return {
      type: AstNodeType.VariableDeclaration,
      name: varToken.value,
      value: this.formatValueTokens(valTokens),
      line: varToken.line,
      column: varToken.column
    };
  }

  private parseMixinDefinition(): MixinDefinitionNode {
    const mixinToken = this.consume(TokenType.AtKeyword, "Expected @mixin");
    const nameToken = this.consume(TokenType.Text, "Expected mixin name");

    const parameters: string[] = [];
    if (this.peek().type === TokenType.OpenParen) {
      this.advance();
      while (!this.isAtEnd() && this.peek().type !== TokenType.CloseParen) {
        if (this.peek().type === TokenType.Variable) {
          parameters.push(this.advance().value);
        } else if (this.peek().type === TokenType.Comma) {
          this.advance();
        } else {
          this.advance();
        }
      }
      this.consume(TokenType.CloseParen, "Expected ')' after mixin parameters");
    }

    this.consume(TokenType.OpenBrace, "Expected '{' before mixin body");
    const children: AstNode[] = [];
    while (!this.isAtEnd() && this.peek().type !== TokenType.CloseBrace) {
      const child = this.parseStatement();
      if (child !== null) {
        children.push(child);
      }
    }
    this.consume(TokenType.CloseBrace, "Expected '}' after mixin body");

    return {
      type: AstNodeType.MixinDefinition,
      name: nameToken.value,
      parameters,
      children,
      line: mixinToken.line,
      column: mixinToken.column
    };
  }

  private parseIncludeDirective(): IncludeDirectiveNode {
    const includeToken = this.consume(TokenType.AtKeyword, "Expected @include");
    const nameToken = this.consume(TokenType.Text, "Expected mixin name to include");

    const args: string[] = [];
    if (this.peek().type === TokenType.OpenParen) {
      this.advance();
      let currentArg = "";
      while (!this.isAtEnd() && this.peek().type !== TokenType.CloseParen) {
        if (this.peek().type === TokenType.Comma) {
          args.push(currentArg.trim());
          currentArg = "";
          this.advance();
        } else {
          currentArg += (currentArg.length > 0 ? " " : "") + this.advance().value;
        }
      }
      if (currentArg.trim().length > 0) {
        args.push(currentArg.trim());
      }
      this.consume(TokenType.CloseParen, "Expected ')' after mixin arguments");
    }

    if (this.peek().type === TokenType.Semicolon) {
      this.advance();
    }

    return {
      type: AstNodeType.IncludeDirective,
      name: nameToken.value,
      arguments: args,
      line: includeToken.line,
      column: includeToken.column
    };
  }

  private parseRuleOrProperty(): AstNode {
    const startToken = this.peek();
    const tokenBuffer: Token[] = [];

    while (
      !this.isAtEnd() &&
      this.peek().type !== TokenType.Colon &&
      this.peek().type !== TokenType.OpenBrace &&
      this.peek().type !== TokenType.Semicolon &&
      this.peek().type !== TokenType.CloseBrace
    ) {
      tokenBuffer.push(this.advance());
    }

    if (this.peek().type === TokenType.Colon) {
      const isProperty = this.lookaheadIsPropertyDeclaration();

      if (isProperty) {
        const propName = tokenBuffer.map((t) => t.value).join(" ").trim();
        this.consume(TokenType.Colon, "Expected ':'");

        const valueTokens: Token[] = [];
        while (
          !this.isAtEnd() &&
          this.peek().type !== TokenType.Semicolon &&
          this.peek().type !== TokenType.CloseBrace &&
          this.peek().type !== TokenType.OpenBrace
        ) {
          valueTokens.push(this.advance());
        }

        if (this.peek().type === TokenType.Semicolon) {
          this.advance();
        }

        return {
          type: AstNodeType.PropertyDeclaration,
          property: propName,
          value: this.formatValueTokens(valueTokens),
          line: startToken.line,
          column: startToken.column
        };
      } else {
        tokenBuffer.push(this.advance());
        while (
          !this.isAtEnd() &&
          this.peek().type !== TokenType.OpenBrace &&
          this.peek().type !== TokenType.Semicolon &&
          this.peek().type !== TokenType.CloseBrace
        ) {
          tokenBuffer.push(this.advance());
        }
      }
    }

    if (this.peek().type === TokenType.OpenBrace) {
      this.advance();
      const rawSelectors = this.formatSelectorTokens(tokenBuffer);
      const selectors = rawSelectors
        .split(",")
        .map((s) => s.trim())
        .filter((s) => s.length > 0);

      const children: AstNode[] = [];
      while (!this.isAtEnd() && this.peek().type !== TokenType.CloseBrace) {
        const child = this.parseStatement();
        if (child !== null) {
          children.push(child);
        }
      }

      this.consume(TokenType.CloseBrace, "Expected '}' after rule block");

      return {
        type: AstNodeType.Rule,
        selectors,
        children,
        line: startToken.line,
        column: startToken.column
      };
    }

    if (this.peek().type === TokenType.Semicolon) {
      this.advance();
    }

    return {
      type: AstNodeType.PropertyDeclaration,
      property: tokenBuffer.map((t) => t.value).join(" ").trim(),
      value: "",
      line: startToken.line,
      column: startToken.column
    };
  }

  private formatValueTokens(tokens: Token[]): string {
    let result = "";
    for (let i = 0; i < tokens.length; i++) {
      const t = tokens[i];
      const prev = i > 0 ? tokens[i - 1] : null;

      if (result.length === 0) {
        result += t.value;
        continue;
      }

      if (t.type === TokenType.Comma) {
        result += ",";
      } else if (t.type === TokenType.CloseParen) {
        result += ")";
      } else if (prev && prev.type === TokenType.OpenParen) {
        result += t.value;
      } else if (prev && prev.type === TokenType.Comma) {
        result += " " + t.value;
      } else {
        result += " " + t.value;
      }
    }
    return result.trim();
  }

  private formatSelectorTokens(tokens: Token[]): string {
    let result = "";
    for (let i = 0; i < tokens.length; i++) {
      const t = tokens[i];
      const prev = i > 0 ? tokens[i - 1] : null;

      if (result.length === 0) {
        result += t.value;
        continue;
      }

      if (t.type === TokenType.Colon) {
        result += t.value;
      } else if (prev && prev.type === TokenType.Colon) {
        result += t.value;
      } else if (t.value.startsWith(".") && prev && prev.value === "&") {
        result += t.value;
      } else if (t.type === TokenType.Comma) {
        result += ", ";
      } else if (prev && prev.type === TokenType.Comma) {
        result += t.value;
      } else {
        result += " " + t.value;
      }
    }
    return result.trim();
  }

  private lookaheadIsPropertyDeclaration(): boolean {
    let offset = 1;
    while (this.current + offset < this.tokens.length) {
      const t = this.tokens[this.current + offset];
      if (t.type === TokenType.OpenBrace) {
        return false;
      }
      if (t.type === TokenType.Semicolon || t.type === TokenType.CloseBrace) {
        return true;
      }
      offset++;
    }
    return false;
  }

  private peek(): Token {
    return this.tokens[this.current];
  }

  private advance(): Token {
    if (!this.isAtEnd()) {
      this.current++;
    }
    return this.tokens[this.current - 1];
  }

  private isAtEnd(): boolean {
    return this.peek().type === TokenType.EndOfFile;
  }

  private consume(type: TokenType, errorMessage: string): Token {
    if (this.peek().type === type) {
      return this.advance();
    }
    const token = this.peek();
    throw new Error(
      `SyntaxError: ${errorMessage} at line ${token.line}, column ${token.column}. Found '${token.value}' instead.`
    );
  }
}
