name: New Offer

on:
  schedule:
    - cron: '10 21 * * *'
  workflow_dispatch:

jobs:
  bounty:
      runs-on: ubuntu-latest
      permissions:
        issues: write
      env:
        GH_TOKEN: ${{ github.token }}

      steps:
        - uses: actions/checkout@v7
        
        - name: Generate Bounty
          run: 'sudo chmod u+x "./bounty.sh" && bash -c "./bounty.sh"'
